cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
EOF
- name: install dependencies
  yum: pkg={{item}} state=present
  with_items:
    - gcc-c++
    - openssl-devel
    - /usr/bin/c_rehash

- name: configure make squidß
  shell: |
    ./configure \
      --prefix=/usr \
      --includedir=/usr/include \
      --datadir=/usr/share \
      --bindir=/usr/sbin \
      --libexecdir=/usr/lib/squid \
      --localstatedir=/var \
      --sysconfdir=/etc/squid \
      --with-logdir=/var/log/squid \
      --with-openssl \
      --enable-ssl-crtd
  args:
    chdir: /tmp/squid-3.5.28/

- name: make squid
  shell: make
  args:
    chdir: /tmp/squid-3.5.28/

- name: make install squid
  shell: make install
  args:
    chdir: /tmp/squid-3.5.28/

- name:  Copy minimal squid.conf
  copy:
    src: files/squid.conf
    dest: /etc/squid/squid.conf
    owner: root
    mode: 0755

- name:  Copy squid startup init.d
  copy:
    src: files/squid.init
    dest: /etc/init.d/squid
    owner: root
    mode: 0755
- name:  Copy https acl file
  copy:
    src: files/allowed_https_sites.acl
    dest: /etc/squid/allowed_https_sites.acl
    owner: root
    mode: 0755

- name:  squid log dir
  file:
    path: /var/log/squid
    state: directory
    mode: 0777


  # we need to have ip forwarding enabled
- name: enable ip forwarding
  command: sysctl -w net.ipv4.ip_forward=1

- name: persist ip forwarding config
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward = 1"

- name: iptables flush PREROUTING chain
  iptables:
    flush: true
    table: nat
    chain: PREROUTING

- name: iptables forward 80 to 3128
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 3128
    comment: Redirect http web traffic to port 3128

- name: iptables forward 443 to 3130
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 443
    jump: REDIRECT
    to_ports: 3130
    comment: Redirect https web traffic to port 3130

- name: save iptable rules
  command: "service iptables save"

- name: Changing selinx policy
  selinux:
    policy: targeted
    state: permissive

- name: initalize ssl certificate
  command: /usr/lib/squid/ssl_crtd -c  -s /var/log/squid/ssl_db

- name: restart service squid
  service:
    name: squid
    state: restarted
    enabled: yes
