- name: Configure telegraf conf file
  template:
        src: ../files/telegraf.j2
        dest: /etc/telegraf/telegraf.conf
        mode: 0777
- name: restart service telegraf
  when:    ansible_distribution == "RedHat" and ansible_distribution_major_version == "6"
  service:
     name: telegraf
     state: restarted
